// Each entry: dial code, exact local digit count, and format mask (X = digit)
export const COUNTRY_CODES = [
  { code: 'US', name: 'United States',  dial: '+1',   digits: 10, format: '(XXX) XXX-XXXX' },
  { code: 'CA', name: 'Canada',         dial: '+1',   digits: 10, format: '(XXX) XXX-XXXX' },
  { code: 'GB', name: 'United Kingdom', dial: '+44',  digits: 10, format: 'XXXX XXX XXXX'  },
  { code: 'AU', name: 'Australia',      dial: '+61',  digits: 9,  format: 'XXX XXX XXX'    },
  { code: 'FR', name: 'France',         dial: '+33',  digits: 9,  format: 'X XX XX XX XX'  },
  { code: 'DE', name: 'Germany',        dial: '+49',  digits: 10, format: 'XXXX XXXXXX'    },
  { code: 'IT', name: 'Italy',          dial: '+39',  digits: 10, format: 'XXX XXXX XXXX'  },
  { code: 'ES', name: 'Spain',          dial: '+34',  digits: 9,  format: 'XXX XXX XXX'    },
  { code: 'RU', name: 'Russia',         dial: '+7',   digits: 10, format: 'XXX XXX XX XX'  },
  { code: 'TR', name: 'Turkey',         dial: '+90',  digits: 10, format: 'XXX XXX XXXX'   },
  { code: 'IN', name: 'India',          dial: '+91',  digits: 10, format: 'XXXXX XXXXX'    },
  { code: 'PK', name: 'Pakistan',       dial: '+92',  digits: 10, format: 'XXX XXX XXXX'   },
  { code: 'CN', name: 'China',          dial: '+86',  digits: 11, format: 'XXX XXXX XXXX'  },
  { code: 'JP', name: 'Japan',          dial: '+81',  digits: 10, format: 'XXX XXXX XXXX'  },
  { code: 'KR', name: 'South Korea',    dial: '+82',  digits: 10, format: 'XX XXXX XXXX'   },
  { code: 'PH', name: 'Philippines',    dial: '+63',  digits: 10, format: 'XXX XXX XXXX'   },
  { code: 'ID', name: 'Indonesia',      dial: '+62',  digits: 10, format: 'XXX XXXX XXXX'  },
  { code: 'BR', name: 'Brazil',         dial: '+55',  digits: 11, format: 'XX XXXXX XXXX'  },
  { code: 'MX', name: 'Mexico',         dial: '+52',  digits: 10, format: 'XX XXXX XXXX'   },
  { code: 'ZA', name: 'South Africa',   dial: '+27',  digits: 9,  format: 'XX XXX XXXX'    },
  { code: 'NG', name: 'Nigeria',        dial: '+234', digits: 10, format: 'XXX XXX XXXX'   },
  { code: 'SN', name: 'Senegal',        dial: '+221', digits: 9,  format: 'XX XXX XXXX'    },
  { code: 'DZ', name: 'Algeria',        dial: '+213', digits: 9,  format: 'XXX XX XX XX'   },
  { code: 'MA', name: 'Morocco',        dial: '+212', digits: 9,  format: 'XX XXX XXXX'    },
  { code: 'SA', name: 'Saudi Arabia',   dial: '+966', digits: 9,  format: 'XX XXX XXXX'    },
  { code: 'AE', name: 'UAE',            dial: '+971', digits: 9,  format: 'XX XXX XXXX'    },
];
